name: Snake

on:
  push:
    branches:
      - main  # Use 'main' instead of 'master'

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user: Raddames-Tonui
          gif_out: github-contribution-grid-snake.gif
